version: '3.7'

services:
  # -------- USER DB --------
  user-db:
    container_name: user-db
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -c wal_level=logical -p 5432

  # -------- USER REDIS --------
  user-redis:
    container_name: user-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./redis/data:/data
    labels:
      - "name=redis"
      - "mode=standalone"
  # -------- KAFKA --------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka1:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka1
    ports:
      - "8097:8097"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8099,INTERNAL://kafka3:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    restart: always
