version: '3.7'

services:
  # -------- USER DB --------
  user-db:
    container_name: user-db
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -c wal_level=logical -p 5432

  # -------- USER REDIS --------
  user-redis:
    container_name: user-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./redis/data:/data
    labels:
      - "name=redis"
      - "mode=standalone"