spring:
  application:
    name: user-service
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---

# 로컬
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      max-lifetime: 1200000
      connection-timeout: 10000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#  kafka:
#    bootstrap-servers: http://localhost:1111

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: info
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    org:
      springframework:
        data:
          jpa: INFO
        web: INFO